[package]
name = "egui_sdl2_canvas"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["examples/*"]

[dependencies]
bytemuck = "1.23.0"
egui = { version = "0.27", default-features = false, features = ["bytemuck"] }
sdl2 = "0.37"
sdl2-sys = "0.37"     
